channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=23.0.1
- pip:
  - mlflow<3,>=2.3
  - cloudpickle==1.4.0
  - numpy==1.21.5
  - psutil==5.9.0
  - scikit-learn==1.2.0
  - scipy==1.9.3
  - typing-extensions==4.6.1
name: mlflow-env
